In [69]:
import pandas as pd
import numpy as np
# 读取 Excel 文件
df = pd.read_excel('./data/中国各城市空间权重矩阵(1).xlsx', sheet_name='地理距离矩阵')


In [92]:
# # 获取DataFrame的形状
# shape = df.shape
# print("DataFrame的形状：", shape)

# # 获取DataFrame的列名
# columns = df.columns
# print("DataFrame的列名：", columns)

# # 获取DataFrame的数据类型信息
# dtypes = df.dtypes
# print("DataFrame的数据类型信息：")
# print(dtypes)

# # 获取DataFrame的摘要统计信息
# summary = df.describe()
# print("DataFrame的摘要统计信息：")
# print(summary)
df

proveng       cityeng cityseries    city1    city2    city3    city9  \
0     Beijing       Beijing      City1     0.00    96.06   239.46   162.11   
1     Tianjin       Tianjin      City2    96.06     0.00   269.63    93.42   
2       Hebei  Shijiazhuang      City3   239.46   269.63     0.00   363.06   
3       Hebei      Tangshan      City9   162.11    93.42   363.06     0.00   
4       Hebei  Qinghuangdao     City12   266.93   200.99   470.05   108.66   
..        ...           ...        ...      ...      ...      ...      ...   
273   Ningxia      Yinchuan    City600   884.18   955.95   712.93  1042.78   
274   Ningxia    Shizuishan    City601   864.88   942.13   712.21  1025.79   
275   Ningxia       Wuzhong    City602   907.68   974.21   721.68  1063.33   
276  Xinjiang      Wulumuqi    City604  2433.90  2525.47  2340.00  2592.22   
277  Xinjiang      Kelamayi    City605  2666.29  2759.92  2590.30  2821.25   

      city12   city13   city15  ...  City590  City591  City592  City595  \
0     266.93   394.54   326.77  ...  1383.90   988.22  1537.70   903.66   
1     200.99   387.58   331.20  ...  1461.68  1035.38  1619.68   948.00   
2     470.05   184.80   109.09  ...  1226.96   766.38  1395.66   678.54   
3     108.66   474.06   421.57  ...  1545.12  1128.59  1699.74  1041.34   
4       0.00   569.15   522.10  ...  1650.75  1236.22  1803.26  1148.59   
..       ...      ...      ...  ...      ...      ...      ...      ...   
273  1150.30   749.36   730.06  ...   515.52   329.09   692.61   332.77   
274  1131.81   768.90   741.66  ...   519.55   412.18   683.44   410.93   
275  1171.65   739.10   727.42  ...   523.78   254.02   709.63   264.69   
276  2685.20  2417.82  2385.54  ...  1210.86  1865.18  1015.79  1932.21   
277  2909.44  2679.98  2643.04  ...  1503.68  2157.09  1309.31  2220.51   

     City597  City600  City601  City602  City604  City605  
0    1340.78   884.18   864.88   907.68  2433.90  2666.29  
1    1406.61   955.95   942.13   974.21  2525.47  2759.92  
2    1150.32   712.93   712.21   721.68  2340.00  2590.30  
3    1496.18  1042.78  1025.79  1063.33  2592.22  2821.25  
4    1604.59  1150.30  1131.81  1171.65  2685.20  2909.44  
..       ...      ...      ...      ...      ...      ...  
273   464.56     0.00    83.65    75.82  1680.02  1953.97  
274   510.43    83.65     0.00   159.47  1649.81  1917.17  
275   433.10    75.82   159.47     0.00  1710.67  1989.97  
276  1436.67  1680.02  1649.81  1710.67     0.00   310.74  
277  1737.78  1953.97  1917.17  1989.97   310.74     0.00  

[278 rows x 281 columns]

In [106]:
# 提取省份列和矩阵部分（假设矩阵的数据从第2行开始，第2列开始）
provinces = df.iloc[:, 0].values
citys = df.iloc[:, 1].values
matrix = df.iloc[0:, 3:].values
print(len(provinces))
print(len(citys))
print("provinces", provinces[:10])
print("citys", citys[:10])
print(matrix)

278
278
provinces ['Beijing' 'Tianjin' 'Hebei' 'Hebei' 'Hebei' 'Hebei' 'Hebei' 'Hebei'
 'Hebei' 'Hebei']
citys ['Beijing' 'Tianjin' 'Shijiazhuang' 'Tangshan' 'Qinghuangdao' 'Handan'
 'Xingtai' 'Baoding' 'Zhuangjiakou' 'Chengde']
[[   0.     96.06  239.46 ...  907.68 2433.9  2666.29]
 [  96.06    0.    269.63 ...  974.21 2525.47 2759.92]
 [ 239.46  269.63    0.   ...  721.68 2340.   2590.3 ]
 ...
 [ 907.68  974.21  721.68 ...    0.   1710.67 1989.97]
 [2433.9  2525.47 2340.   ... 1710.67    0.    310.74]
 [2666.29 2759.92 2590.3  ... 1989.97  310.74    0.  ]]


In [139]:
# 
distance_matrix = df.iloc[:, 3:]
city_index = 2
distance_matrix.index = df.iloc[:, city_index].values
distance_matrix.columns = df.iloc[:, city_index].values

# 挑选出安徽、江苏、浙江和上海的省份及对应的矩阵数据
selected_provinces = ['Anhui', 'Jiangsu', 'Zhejiang', 'Shanghai']
selected_cities = df[df['proveng'].isin(selected_provinces)]['cityeng'].tolist()
selected_indices = [i for i, prov in enumerate(provinces) if prov in selected_provinces]
selected_matrix = matrix[selected_indices, :]
selected_indices_str = df.values[selected_indices, city_index]
# 打印挑选出的省份及对应的矩阵数据
print("挑选出的省份：", selected_provinces)
print("挑选出的城市：", len(selected_cities), "selected_cities:", selected_cities)
print("挑选出的索引：", selected_indices)
print("对应的矩阵数据：")
print(selected_matrix.shape)
print("selected_matrix\n", selected_matrix)
print("selected_indices_str\n", len(selected_indices_str), selected_indices_str)

挑选出的省份： ['Anhui', 'Jiangsu', 'Zhejiang', 'Shanghai']
挑选出的城市： 41 selected_cities: ['Shanghai', 'Nanjing', 'Wuxi', 'Xuzhou', 'Changzhou', 'Nantong', 'huaian', 'yancheng', 'Yangzhou', 'zhenjiang', 'Taizhou', 'Suqian', 'Hangzhou', 'ningbo', 'Wenzhou', 'Jiaxing', 'Huzhou', 'Shaoxing', 'Jinhua', 'Quzhou', 'Zhoushan', 'Taizhou', 'Lishui', 'Hefei', 'Wuhu', 'Bengbu', 'Huainan', 'Maanshan', 'Huaibei', 'Tongling', 'Anqing', 'Huangshan', 'Chuzhou', 'Fuyang', 'Suzhou', 'suzhou', 'liuan', 'Bozhou', 'chizou', 'xuancheng', 'Lianyungang']
挑选出的索引： [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 186]
对应的矩阵数据：
(41, 278)
selected_matrix
 [[1041.97  955.6   997.79 ... 1566.06 3272.88 3542.88]
 [ 860.69  787.49  766.85 ... 1285.73 2995.23 3268.88]
 [ 980.99  898.94  917.49 ... 1464.53 3173.14 3445.22]
 ...
 [1024.05  960.78  892.4  ... 1304.18 3010.26 3293.63]
 [1019.42  948.3   912.26 ... 1

In [140]:
# distance_matrix[:, selected_cities_str]
# matrix
# distance_matrix
# list
# distance_matrix.values 

City1    City2    City3    City9   City12   City13   City15  \
City1       0.00    96.06   239.46   162.11   266.93   394.54   326.77   
City2      96.06     0.00   269.63    93.42   200.99   387.58   331.20   
City3     239.46   269.63     0.00   363.06   470.05   184.80   109.09   
City9     162.11    93.42   363.06     0.00   108.66   474.06   421.57   
City12    266.93   200.99   470.05   108.66     0.00   569.15   522.10   
...          ...      ...      ...      ...      ...      ...      ...   
City600   884.18   955.95   712.93  1042.78  1150.30   749.36   730.06   
City601   864.88   942.13   712.21  1025.79  1131.81   768.90   741.66   
City602   907.68   974.21   721.68  1063.33  1171.65   739.10   727.42   
City604  2433.90  2525.47  2340.00  2592.22  2685.20  2417.82  2385.54   
City605  2666.29  2759.92  2590.30  2821.25  2909.44  2679.98  2643.04   

          City18   City23   City24  ...  City590  City591  City592  City595  \
City1     141.46   178.80   161.98  ...  1383.90   988.22  1537.70   903.66   
City2     167.86   274.85   178.96  ...  1461.68  1035.38  1619.68   948.00   
City3     103.02   274.56   401.41  ...  1226.96   766.38  1395.66   678.54   
City9     261.06   330.05   144.46  ...  1545.12  1128.59  1699.74  1041.34   
City12    368.82   423.71   190.77  ...  1650.75  1236.22  1803.26  1148.59   
...          ...      ...      ...  ...      ...      ...      ...      ...   
City600   797.58   760.72  1013.65  ...   515.52   329.09   692.61   332.77   
City601   789.82   729.25   985.49  ...   519.55   412.18   683.44   410.93   
City602   811.73   795.52  1044.00  ...   523.78   254.02   709.63   264.69   
City604  2399.36  2262.75  2504.61  ...  1210.86  1865.18  1015.79  1932.21   
City605  2642.96  2491.30  2724.37  ...  1503.68  2157.09  1309.31  2220.51   

         City597  City600  City601  City602  City604  City605  
City1    1340.78   884.18   864.88   907.68  2433.90  2666.29  
City2    1406.61   955.95   942.13   974.21  2525.47  2759.92  
City3    1150.32   712.93   712.21   721.68  2340.00  2590.30  
City9    1496.18  1042.78  1025.79  1063.33  2592.22  2821.25  
City12   1604.59  1150.30  1131.81  1171.65  2685.20  2909.44  
...          ...      ...      ...      ...      ...      ...  
City600   464.56     0.00    83.65    75.82  1680.02  1953.97  
City601   510.43    83.65     0.00   159.47  1649.81  1917.17  
City602   433.10    75.82   159.47     0.00  1710.67  1989.97  
City604  1436.67  1680.02  1649.81  1710.67     0.00   310.74  
City605  1737.78  1953.97  1917.17  1989.97   310.74     0.00  

[278 rows x 278 columns]

In [144]:
# 从城市列表中随机选择25个城市（不包括上海）
selected_index = pd.Index(selected_indices_str)
# 使用 loc 方法选择相应的行和列
selected_data = distance_matrix.loc[selected_index, selected_index]
np.random.seed(42)
print(selected_indices_str[0])
random_cities = np.random.choice(selected_indices_str[1:], 25, replace=False)
print(len(random_cities))
# 将上海添加到随机选择的城市列表中 
# City158 = shanghai
selected_cities_26 = ['City158'] + random_cities.tolist()
print(len(selected_cities_26))
selected_index_26 = pd.Index(selected_cities_26)
# 使用 loc 方法选择相应的行和列


selected_data_26 = selected_data.loc[selected_index_26, selected_index_26]
city_to_city_series = df[['cityeng', 'cityseries']].drop_duplicates().set_index('cityeng')['cityseries'].to_dict()
city_series_to_city = df[['cityeng', 'cityseries']].drop_duplicates().set_index('cityseries')['cityeng'].to_dict()
city_series_26_columns = selected_data_26.columns
city_26_columns = []
for item in city_series_26_columns:
    city_26_columns.append(city_series_to_city[item])
city_26 = pd.DataFrame(selected_data_26.values, index=city_26_columns, columns=city_26_columns)

City158
25
26
(26, 26)


In [145]:
selected_data_26

City158  City223  City213  City212  City233  City174  City201  \
City158     0.00   145.84   156.19   136.34   288.14   121.87   180.37   
City223   145.84     0.00   165.81   200.50   394.74   267.26    89.17   
City213   156.19   165.81     0.00    63.84   253.38   224.34   109.58   
City212   136.34   200.50    63.84     0.00   197.79   171.30   165.46   
City233   288.14   394.74   253.38   197.79     0.00   220.80   361.66   
City174   121.87   267.26   224.34   171.30   220.80     0.00   288.06   
City201   180.37    89.17   109.58   165.46   361.66   288.06     0.00   
City248   392.51   461.78   297.58   267.15   150.08   356.50   402.42   
City234   527.73   660.70   540.29   479.52   292.61   416.00   644.67   
City433   412.91   558.70   499.18   436.86   335.04   292.72   578.45   
City181   258.08   403.60   359.28   300.56   261.47   140.59   428.66   
City232   466.32   584.13   444.70   389.36   191.73   372.37   553.34   
City190   210.06   350.13   267.14   204.21   153.52    96.94   353.52   
City205   359.15   275.66   221.57   281.23   431.87   445.42   191.49   
City238   316.58   441.70   318.24   257.07    84.02   220.54   422.21   
City244    87.81   208.50   132.50    80.26   200.56    92.24   207.50   
City187   219.81   354.13   256.08   192.27   120.45   117.50   349.14   
City216   294.22   278.94   138.50   173.90   283.55   344.43   194.88   
City231   416.88   541.62   412.11   353.07   161.33   316.51   518.50   
City159   286.05   410.45   288.48   226.77    68.93   193.49   391.65   
City243   508.59   640.24   517.98   457.54   269.52   398.46   622.82   
City179   317.38   461.82   385.97   322.75   221.65   195.78   471.49   
City196   157.76   189.52    29.18    40.26   224.21   209.62   138.50   
City160   107.97   233.06   149.95    92.00   180.83    80.86   230.70   
City236   418.88   486.19   321.41   292.75   173.31   382.50   425.02   
City227   361.50   312.30   207.70   255.49   372.19   426.66   223.14   

         City248  City234  City433  ...  City187  City216  City231  City159  \
City158   392.51   527.73   412.91  ...   219.81   294.22   416.88   286.05   
City223   461.78   660.70   558.70  ...   354.13   278.94   541.62   410.45   
City213   297.58   540.29   499.18  ...   256.08   138.50   412.11   288.48   
City212   267.15   479.52   436.86  ...   192.27   173.90   353.07   226.77   
City233   150.08   292.61   335.04  ...   120.45   283.55   161.33    68.93   
City174   356.50   416.00   292.72  ...   117.50   344.43   316.51   193.49   
City201   402.42   644.67   578.45  ...   349.14   194.88   518.50   391.65   
City248     0.00   362.14   473.87  ...   269.30   251.38   241.65   214.35   
City234   362.14     0.00   258.24  ...   308.19   572.67   131.94   253.09   
City433   473.87   258.24     0.00  ...   250.96   589.50   266.37   266.13   
City181   411.55   337.74   155.95  ...   145.01   466.61   278.14   201.52   
City232   230.22   133.97   322.40  ...   254.91   455.20    62.83   181.09   
City190   302.26   319.74   232.93  ...    33.07   359.84   220.82   106.11   
City205   401.86   723.42   717.44  ...   468.98   153.25   591.50   484.59   
City238   216.86   222.48   257.33  ...   103.02   365.07   100.53    31.23   
City244   308.61   452.27   372.35  ...   146.13   254.14   335.38   203.79   
City187   269.30   308.19   250.96  ...     0.00   338.59   200.13    76.93   
City216   251.38   572.67   589.50  ...   338.59     0.00   440.83   341.34   
City231   241.65   131.94   266.37  ...   200.13   440.83     0.00   131.58   
City159   214.35   253.09   266.13  ...    76.93   341.34   131.58     0.00   
City243   339.34    23.49   257.18  ...   288.80   549.23   108.59   231.49   
City179   366.35   245.23   118.00  ...   133.54   471.74   194.00   153.20   
City196   272.30   511.65   476.91  ...   231.02   139.44   383.17   260.32   
City160   296.58   427.81   351.01  ...   121.54   263.87   311.65   180.13   
City236    26.51   366.59   491.41 

In [148]:
city_to_city_series

{'Beijing': 'City1',
 'Tianjin': 'City2',
 'Shijiazhuang': 'City3',
 'Tangshan': 'City9',
 'Qinghuangdao': 'City12',
 'Handan': 'City13',
 'Xingtai': 'City15',
 'Baoding': 'City18',
 'Zhuangjiakou': 'City23',
 'Chengde': 'City24',
 'Cangzhou': 'City25',
 'Langfang': 'City30',
 'Hengshui': 'City33',
 'Taiyuan': 'City36',
 'Datong': 'City38',
 'Yangquan': 'City39',
 'changzhi': 'City40',
 'Jincheng': 'City42',
 'Shuozhou': 'City44',
 'jinzhong': 'City45',
 'Yuncheng': 'City47',
 'Xinzhou': 'City50',
 'Linfen': 'City52',
 'lvliang': 'City55',
 'Huhehaote': 'City56',
 'Baotou': 'City57',
 'Wuhai': 'City58',
 'Chifeng': 'City59',
 'Tongliao': 'City60',
 'eerduosi': 'City62',
 'hulunbeier': 'City63',
 'bayannaoer': 'City69',
 'wulanchabu': 'City70',
 'Shenyang': 'City75',
 'Dalian': 'City77',
 'Anshan': 'City81',
 'Fushun': 'City83',
 'Benxi': 'City84',
 'Dandong': 'City85',
 'Jinzhou': 'City88',
 'Yingkou': 'City90',
 'Fuxin': 'City93',
 'Liaoyao': 'City94',
 'Panjing': 'City95',
 'Tieling'

In [150]:
city_series_to_city

{'City1': 'Beijing',
 'City2': 'Tianjin',
 'City3': 'Shijiazhuang',
 'City9': 'Tangshan',
 'City12': 'Qinghuangdao',
 'City13': 'Handan',
 'City15': 'Xingtai',
 'City18': 'Baoding',
 'City23': 'Zhuangjiakou',
 'City24': 'Chengde',
 'City25': 'Cangzhou',
 'City30': 'Langfang',
 'City33': 'Hengshui',
 'City36': 'Taiyuan',
 'City38': 'Datong',
 'City39': 'Yangquan',
 'City40': 'changzhi',
 'City42': 'Jincheng',
 'City44': 'Shuozhou',
 'City45': 'jinzhong',
 'City47': 'Yuncheng',
 'City50': 'Xinzhou',
 'City52': 'Linfen',
 'City55': 'lvliang',
 'City56': 'Huhehaote',
 'City57': 'Baotou',
 'City58': 'Wuhai',
 'City59': 'Chifeng',
 'City60': 'Tongliao',
 'City62': 'eerduosi',
 'City63': 'hulunbeier',
 'City69': 'bayannaoer',
 'City70': 'wulanchabu',
 'City75': 'Shenyang',
 'City77': 'Dalian',
 'City81': 'Anshan',
 'City83': 'Fushun',
 'City84': 'Benxi',
 'City85': 'Dandong',
 'City88': 'Jinzhou',
 'City90': 'Yingkou',
 'City93': 'Fuxin',
 'City94': 'Liaoyao',
 'City95': 'Panjing',
 'City96':

In [153]:

# city_series_26_columns

Index(['City158', 'City223', 'City213', 'City212', 'City233', 'City174',
       'City201', 'City248', 'City234', 'City433', 'City181', 'City232',
       'City190', 'City205', 'City238', 'City244', 'City187', 'City216',
       'City231', 'City159', 'City243', 'City179', 'City196', 'City160',
       'City236', 'City227'],
      dtype='object')

['Shanghai', 'Zhoushan', 'Shaoxing', 'Huzhou', 'Maanshan', 'Nantong', 'ningbo', 'chizou', 'Huaibei', 'Lianyungang', 'yancheng', 'Huainan', 'Taizhou', 'Wenzhou', 'Chuzhou', 'suzhou', 'zhenjiang', 'Jinhua', 'Bengbu', 'Nanjing', 'Suzhou', 'huaian', 'Hangzhou', 'Wuxi', 'Anqing', 'Lishui']


In [1]:
# city_26